### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by alin23** [helixbass/prettier-plugin-coffeescript#1]
Thank you for this plugin! I've been looking for something like this ever since CoffeeScript 2 was launched. It worked perfectly on my codebase!

_I had no idea prettier has support for plugins._

Feel free to close the issue whenever you want, I just couldn't find a better way to thank you.

**Comment by helixbass** [comment]
@alin23 you're welcome! Haven't publicized this yet as the corresponding AST support for Coffeescript hasn't landed yet, was just making plans with @GeoffreyBooth (Coffeescript maintainer) to start doing so this month

Please do open an issue to let me know if you find any "rough edges" (or have opinions about the way things are formatted), the biggest thing I'm currently aware of is that multiline herecomments will probably not indent themselves nicely
