### ISSUE TITLE
Wrongly removed parentheses around expression over class prototype

### ISSUE THREAD

**Issue by eugenet8k** [helixbass/prettier-plugin-coffeescript#165]
This valid CoffeeScript code

```
export default class MyClass extends MyOtherClass
  DEFAULTS: {
    (@::DEFAULTS)...
    a: 1
    b: 1
  }
```

Prettier turns to invalid one

```
export default class MyClass extends MyOtherClass
  DEFAULTS: {
    @::DEFAULTS...
    a: 1
    b: 1
  }
```

Thanks for your attention!

**Comment by eugenet8k** [comment]
Same problem for existential expressions

Working code:
```
{(opts?.data?.root)..., (opts?.data)...}
```

is turned to broken:
```
{opts?.data?.root..., opts?.data...}
```

**Comment by helixbass** [comment]
Ok this is really a Coffeescript parser bug (opened https://github.com/jashkenas/coffeescript/issues/5291)

But in the meantime I updated the Prettier plugin to ensure parentheses around these non-parsing object spread expressions

I can release a new version of the Prettier plugin soon, but in the meantime you could use a Github dependency if you want:
```
yarn add --dev github:helixbass/prettier-plugin-coffeescript#d63278a7
```

**Comment by eugenet8k** [comment]
@helixbass thank you! Stellar response speed and support!

Btw is your forked prettier will land in official prettier with a first class support for coffeescript? Or is it going to be continuously supported via fork?

**Comment by helixbass** [comment]
> Btw is your forked prettier will land in official prettier with a first class support for coffeescript? Or is it going to be continuously supported via fork?

I think we'll be able to land the modifications in official prettier. There's an open PR for all of the changes needed to support Coffeescript, but no-one from Prettier core team has stepped up and really reviewed it

Now that we've released the Prettier plugin, I'll dig back into the Prettier side soon and try and help get it merged

**Comment by GeoffreyBooth** [comment]
> There's an open PR for all of the changes needed to support Coffeescript, but no-one from Prettier core team has stepped up and really reviewed it

Try cc'ing @lydell, he’s a former maintainer of CoffeeScript who is/was also active in Prettier, he might be able to help.

I'm happy to fast-track a 2.5.1 release of CoffeeScript to get out various bugfixes.
