### ISSUE TITLE
RFE: support a more up to date prettier version. 

### ISSUE THREAD

**Issue by AntonioMeireles** [helixbass/prettier-plugin-coffeescript#170]
@helixbass 

first, once again, let me give an **HUGE** thank you for your immense hard work making coffeescript cool and handy :-) 

Could you please, when you have time, rebase your prettier fork against a more recent one ?

Many thanks in advance!

**Comment by helixbass** [comment]
Ok I updated the prettier fork to include current Prettier `master` (so v2.1.0-dev), updated this plugin to use that as its Prettier dependency and released a beta version of the plugin

So can you try updating your Prettier + plugin dependencies and let me know if everything is working ok? Eg:
```
yarn add --dev prettier-plugin-coffeescript@0.5.1-beta.1 github:helixbass/prettier#prettier-v2.1.0-dev.100-gitpkg
```

**Comment by AntonioMeireles** [comment]
```diff
-    "prettier": "github:helixbass/prettier#b8818ebd",
-    "prettier-plugin-coffeescript": "^0.1.4"
+    "prettier": "^github:helixbass/prettier#prettier-v2.1.0-dev.100-gitpkg",
+    "prettier-plugin-coffeescript": "^0.1.5-beta.1"
```
**THANKS**, once again! at sight, on quick testing, working nicely here. (pasting diff above to help others as there was a typo on your comment above (_0.5.1-beta.1_ instead of **0.1.5-beta.1**). issue closable after README is updated, imho.

**Comment by helixbass** [comment]
Ah thanks for the correction, updated my comment

I updated the README installation instructions to reference the new Prettier dependency

Will probably promote the beta and release `v0.1.5` this weekend
