### ISSUE TITLE
No parser could be inferred for file: [something].coffee

### ISSUE THREAD

**Issue by localhostdotdev** [helixbass/prettier-plugin-coffeescript#79]
Sorry as it's very basic, but I tried `yarn add https://github.com/helixbass/prettier-plugin-coffeescript`, and `yarn global add github.com/helixbass/prettier-plugin-coffeescript`.

I also tried `yarn add prettier-plugin-coffeescript`, and `yarn global add prettier-plugin-coffeescript` but it's 0.0.6 released 13 days ago (https://www.npmjs.com/package/prettier-plugin-coffeescript) so that might be why it doesn't work. 

And it doesn't seem to catch the .coffee files.

`prettier-ruby` works fine in my setup so I don't see why this one wouldn't.

I'm definitely not a node expert so 

Thanks!

- `node -v`: `v8.9.3`
- `npm -v`: `6.7.0`
- `yarn -v`: `1.3.2`

**Comment by helixbass** [comment]
Hi,

So first just a heads up, this plugin is still pretty "alpha" - there is no documentation in the README yet (sorry), and it's possible you'll run into broken/unstable formatting

But if you want to try it out, I'm happy to try and help you get it running

I just tried this and it worked:

1. Create new project with new `package.json`

1. `yarn add --dev prettier-plugin-coffeescript`

1. Created new `test.coffee` file in the project with these contents:
```
x=->
    a
```

4. From the command line, running `yarn prettier test.coffee` correctly prints
```
x = ->
  a
```

So it might be worth checking that that works on your machine as well (with a fresh test project)

And so then for your project, I'm not sure how you're running Prettier but first I'd try the same thing from the command line
```
$ yarn prettier path/to/some/file.coffee
```

If that doesn't work:

The plugin currently requires "forked" (`github`-based) dependencies of `prettier` and `coffeescript` as its dependencies. So my best guess is that if you're adding `prettier-plugin-coffeescript` to a project that already includes `prettier` and/or `coffeescript` as dependencies, it may not be using the correct versions of those dependencies

So I would try:

1. Remove your existing `coffeescript` and `prettier` dependencies
```
$ yarn remove coffeescript
$ yarn remove prettier
```

2. Then try adding `prettier-plugin-coffeescript` as a local dev dependency
```
$ yarn add --dev prettier-plugin-coffeescript
```

3. Sometimes I've seen `yarn` get confused about Github dependency versions, so for good measure I'd do
```
$ rm yarn.lock && yarn install
```

Then try again to format a file from the command line
```
$ yarn prettier path/to/some/file.coffee
```

Let me know if that works

And then I can try and help make sure the project is set up to run Prettier how you normally would. Eg if you're currently using Prettier to format Ruby or JS in the same project, I'd be curious if using the different `prettier` dependency causes any problems (it shouldn't)

I'll be adding some `README` documentation and continuing to stabilize the plugin over the next month or so, so feel free to check back if you'd rather wait until it's more stable

**Comment by localhostdotdev** [comment]
Thanks :) Making it a devDependency does make a lot of sense.
